name: querys_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.3.1
  
  flutter:
    sdk: flutter
  firebase_database: ^10.5.4
  firebase_ui_firestore: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
